name: Security Scan

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1" # Tous les lundis à 03:00

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL
